# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1024)),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 11, 12, 8, 51, 56, 657841, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='peopleFormid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(max_length=128)),
                ('formId', models.CharField(max_length=128)),
                ('time', models.DateTimeField(default=datetime.datetime(2017, 11, 12, 8, 51, 56, 657323, tzinfo=utc))),
            ],
        ),
    ]
