# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oflMsgForm', '0005_auto_20171112_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 8, 59, 23, 684019, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='peopleformid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 8, 59, 23, 683596, tzinfo=utc)),
        ),
    ]
