# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oflMsgForm', '0006_auto_20171112_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 9, 4, 0, 431730, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='peopleformid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 9, 4, 0, 431237, tzinfo=utc)),
        ),
    ]
