# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 09:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('oflMsgForm', '0007_auto_20171112_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoken',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 9, 7, 8, 810025, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='peopleformid',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 9, 7, 8, 809560, tzinfo=utc)),
        ),
    ]
