# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('finish_time', models.DateTimeField(auto_now=True)),
                ('place', models.CharField(max_length=400)),
                ('methods', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=200)),
                ('serviceid', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tel', models.CharField(max_length=11)),
                ('psd', models.CharField(blank=True, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=50)),
                ('longtitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rd3', models.CharField(max_length=200)),
                ('session_key', models.CharField(max_length=200)),
                ('openid', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_in_week', models.IntegerField(choices=[(1, '星期一'), (2, '星期二'), (3, '星期三'), (4, '星期四'), (5, '星期五'), (6, '星期六'), (7, '星期天')])),
                ('time', models.IntegerField()),
                ('people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiv.People')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=200)),
                ('nickname', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('vatarUrl', models.CharField(max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('isServiceP', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiv.Place'),
        ),
    ]
