# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='language',
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='isdeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='state',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='psd',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
